version: '3'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
  eureka:
    container_name: eureka
    build:
      context: ./eureka/
      dockerfile: Dockerfile
    volumes:
      - ./eureka/:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - "8761:8761"
  auth:
    container_name: auth
    build:
      context: ./auth/
      dockerfile: Dockerfile
    volumes:
      - ./auth/:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - "8555:8555"
      - "5006:5006"
    depends_on:
      eureka:
        condition: service_started
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017"
      SERVICE_URL_DEFAULT_ZONE: "http://eurekauser:eureka!@eureka:8761/eureka"
      SPRING_DATA_REDIS_HOST: "redis"
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    volumes:
      - ./api-gateway/:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - "8765:8765"
      - "5005:5005"
    environment:
      SERVICE_URL_DEFAULT_ZONE: "http://eurekauser:eureka!@eureka:8761/eureka"
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongodb:27017"
    depends_on:
      mongodb:
        condition: service_started